fix(pkg): Fix version file generation for Python 3.6 builds
Re-introduces `setup_requires` to `setup.cfg` with a strict
`python_version == '3.6'` marker.

This ensures that `setuptools_scm` is invoked correctly by the older
version of `setuptools` used in the Python 3.6 build environment,
which fixes the `ImportError: cannot import name '__version__'` during
testing.

The version marker prevents this from conflicting with the build-time
dependencies of newer Python versions, which are defined in
`pyproject.toml`.